{'stack':{'type':'Stack',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'Switch+',
          'title':'Switch+ 0.0.2 - Smurfat release',
          'position':(560, 486),
          'size':(417, 342),
          'icon':'juggler.ico',

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuImageList',
             'label':'&Imagelist',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuImageListNew',
                   'label':'&New imagelist',
                  },
                  {'type':'MenuItem',
                   'name':'menuImagelistHighres',
                   'label':'Only highres images (default)',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuOptions',
             'label':'&Options',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuOptionsRandom',
                   'label':'Random wallpaper order',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuOptionsAutoStart',
                   'label':'Automatic startup',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuEffects',
             'label':'&Artistic effects',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEffectsNone',
                   'label':'&No effect',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuEffectsSunset',
                   'label':'&Sunset effect',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuEffectsSepia',
                   'label':'Se&pia effect (experimental)',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuEffectsNegative',
                   'label':'Ne&gative effect',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuEffectsGreyscale',
                   'label':'&Greyscale effect',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuPerformance',
             'label':'&Performance',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuPerformanceNEAREST',
                   'label':'Low quality, very high speed (Nearest neighbour)',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuPerformanceBILINEAR',
                   'label':'Medium quality, high speed (Bilinear)',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuPerformanceBICUBIC',
                   'label':'Good quality, normal speed (Bicubic)',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuPerformanceANTIALIAS',
                   'label':'Excellent quality, low speed (Antialias)',
                   'checkable':1,
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'cmdNext', 
    'position':(65, 30), 
    'size':(80, -1), 
    'label':'Change now!', 
    'toolTip':'Change the wallpaper now!', 
    },

{'type':'TextArea', 
    'name':'txtInfo', 
    'position':(5, 65), 
    'size':(400, 225), 
    'alignment':'left', 
    },

{'type':'StaticText', 
    'name':'txtInterval', 
    'position':(10, 10), 
    'size':(149, -1), 
    'text':'Wallpaper interval (seconds)', 
    },

{'type':'Spinner', 
    'name':'spnInterval', 
    'position':(10, 30), 
    'size':(52, -1), 
    'max':7200, 
    'min':1, 
    'toolTip':'Change the wallpaper timeout (seconds)', 
    'value':3600, 
    },

{'type':'StaticBox', 
    'name':'boxBorder', 
    'position':(0, -5), 
    'size':(409, 300), 
    },

] # end components
} # end background
] # end backgrounds
} }
